### PR TITLE
add-templates

### PR DESCRIPTION
**Pull request by Daniel-Xu**

### CODE REVIEW

**Comment by felixbuenemann** [comment]
@Daniel-Xu Do you have some info about this PR?

I'm maintaining this gem, but I'm not a dockyard employee, so a PR that adds a bunch of files without a description/reasoning is not very useful to me.

**Comment by Daniel-Xu** [comment]
@felixbuenemann  Sorry for the inconvenience, this PR is generated based on some templates. The purpose of this PR is tried to add `contribution templates`, `Pull request templates`, `Issue templates` to almost all the repos we(Dockyard) have. Feel free to close it if it's not appropriate.

**Comment by felixbuenemann** [comment]
Thanks for the info. Just leave the PR open, I'll have a look at it the next time I work on this project. I'm currently busy woking on other projects, so it'll likely be some time until I get to it.

**Comment by Daniel-Xu** [comment]
Will close this PR but keep the branch for now.

**Pull request closed without merging**
