### PR TITLE
Fix error where visitor requires 2nd argument in Arel v6

### PR DESCRIPTION
**Pull request by BenMorganIO**
After testing @crossroads changes, I think its worthy of getting this into the project. LMKWYT

### CODE REVIEW

**Comment by AlexEmerson** [comment]
Is there any chance to have the request merged? Have this problem with wrong number of arguments for  visitor.

**Comment by danmcclain** [comment]
@AlexEmerson if you look at #30, which shares a lot of code with this, I have concerns about potentially improper string escaping, which could allow sql injection

**Comment by AlexEmerson** [comment]
Thanks for the reply. It makes sense, keep up your great job. Unfortunately, can't help you guys here. Since I don't need to insert uses' data into sql query gonna use @crossroads's version for a while.

**Comment by felixbuenemann** [comment]
The code from the crossroads fork has been merged.

**Pull request closed without merging**
