### PR TITLE
Root false option

### PR DESCRIPTION
**Pull request by BenMorganIO**
This PR adds the functionality to set root to false. The only problem is that it constrains to just having a root key and needs more work.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Another problem is that the root shouldn't be be dependent on the table name. Assume that you have a model called `Spree::Product`. AMS would print out `products` as you root key. In this project, we would instead print out `spree_products`. Is there a way to demodularize the root key and remove the table name dependency?

**Comment by danmcclain** [comment]
@benmorganio here is where the table name is determined: https://github.com/dockyard/postgres_ext-serializers/blob/master/lib/postgres_ext/serializers/active_model/array_serializer.rb#L119. I'd like the solution for setting/removing the table name to happen in the SQL side to avoid parsing the json on the ruby side

**Comment by BenMorganIO** [comment]
I've been working on trying to add the feature for about three or four hours. Its absolutely over my head. I think a starting place would be refactoring the code. How well tested is the codebase?

**Comment by danmcclain** [comment]
It ensures the output is right?  It doesn't test these private methods. If you can just have the line I linked to above respect the root name passed in, I can work on removing the root name when it's set to false

**Comment by felixbuenemann** [comment]
I agree with @danmcclain that if this feature were to be added, it should be handled in the database, not by parsing the resulting JSON because that adds quite some overhead.

I'm closing this PR, but feel free to create a new one, if you come up with a way to do it in postgres.
I might add this feature in the future, but it's pretty low priority. In most cases it should be pretty easy to adjust the client code to look for the root key.

**Pull request closed without merging**
